### ISSUE TITLE
Rename the plugin?

### ISSUE THREAD

**Issue by mtelka** [jaraco/pytest-home#5]
The plugin's entry point is named `pytest home` so it suffers similar problems as [pytest-enabler did](https://github.com/jaraco/pytest-enabler/issues/12).  Maybe you want to rename this plugin as well?

**Comment by jaraco** [comment]
Thanks! Your work laying out the history made this change easy and quick to fix. I wouldn't have remembered what was the correct incantation without looking at the prior history.

Released in 0.6.
